- id: spectral
  name: spectral
  entry: "spectral lint"
  language: node
  "files": \.(yml|yaml)$
  args: []
  require_serial: false
  additional_dependencies: ["@stoplight/spectral-cli@6.1.1"]
  minimum_pre_commit_version: "0"
